import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import StoreProvidor from "@/redux/StoreProvidor";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{ width: "100vw", backgroundColor: "azure", height: "100vh" }}
        className={inter.className}
      >
        <StoreProvidor>{children}</StoreProvidor>
      </body>
    </html>
  );
}
