import { Box } from "@mui/material";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ width: "100vw" }} className={inter.className}>
        {/* <Box
          sx={{
            border: "1px solid black",
            boxSizing: "border-box",
            padding: {
              xs: "0 0.5% 0 0.5%",
              sm: "0.5% 2% 0 2%",
              md: "1% 4% 0 4%",
              lg: "1% 5% 0 5%",
              xl: "1% 6% 0 6%",
            },
            height: "100%",
          }}
        > */}
        {children}
        {/* </Box> */}
      </body>
    </html>
  );
}
